version: '3.8'
services:
  app-k8s:
    image: emmoro/app-k8s:v1
    container_name: app-k8s
    ports:
      - "8180:8180"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  mysql-data: