kind: Service
apiVersion: v1
metadata:
  name: app-k8s
  labels:
    name: app-k8s
spec:
  ports:
    - nodePort: 30163
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: app-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s
spec:
  selector:
    matchLabels:
      app: app-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: app-k8s
    spec:
      containers:
        - name: app-k8s
          image: emmoro/app-k8s:v1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-conf
                  key: name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password