apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: dGVzdHVzZXI=
 password: dGVzdHVzZXJAMTIz
# Converter username to base 64 - echo -n 'testuser' | base64 == dGVzdHVzZXI=
# Converter password to base 64 - echo -n 'testuser@123' | base64 == dGVzdHVzZXJAMTIz